// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingConvention
{
    internal sealed partial class Vsix
    {
        public const string Id = "51680286-a796-4437-96c7-9cbdd354ed2f";
        public const string Name = " Coding Convention";
        public const string Description = @"This project is about to ensure and automate some coding conventions in the solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Quoc Nguyen";
        public const string Tags = "Coding Standard, Cleanup, Tools, Coding Convention";
    }
}
